version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: devi96
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: usuarios_db
    ports:
      - "5432:5432"